name: eSachse Limited
bio: a digital consulting company specialized in mobile applications
description: home of eSachse limited
url: 'http://www.esachse.co.uk'
permalink: '/:title/'
twitter: 'https://twitter.com/SachseInTheCity'
github: 'https://github.com/SachseInTheHub'
email: nelsonsachse@gmail.com
authors:
  nelsonsachse:
    name: Nelson Sachse
    bio: Developer from eSachse
    external-image: false
    twitter: SachseInTheCity
width: normal
projects: false
about: false
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://esachse.co.uk'
